### ISSUE TITLE
I like to compare notes

### ISSUE THREAD

**Issue by hosseinmoein** [BoostGSoC17/data_frame#2]
I like what you have done here. I have taken a different approach to solve the same problem. Please take a look: https://github.com/hosseinmoein/DataFrame
I would like to compare notes and discuss design considerations you went through

**Comment by yimyom** [comment]
if you're interested in being a student for GSoC 2019 and improve the
data.frame in ublas, you're most welcome.
Let's talk about it together
David

**Comment by hosseinmoein** [comment]
Actually my intentions were to compare and contracts your approach against my approach so you can improve your data.frame and I can improve my DataFrame.

Best,
Hossein

**Comment by yimyom** [comment]
I'm not sure I understand: do you want to participate in GSoC 2019 ?
